# Uncommented options are not recommended for modification
# 未标注释的选项建议不要修改

baseURL = 'http://kawa1planet.fun/'
languageCode = 'en-us'

# website title
# 网站标题
title = 'Kawa1Planet'
# theme
# 主题
theme = "NewBee"
# default content of website
# 网站默认语言
defaultContentLanguage = "zh"
# whether to use robots.txt
# 是否使用 robots.txt
enableRobotsTXT = true
# whether to use git info
# 是否使用 git info
enableGitInfo = false
# length of summary
# 摘要的字数限制
summaryLength = 100

# If true, auto-detect Chinese/Japanese/Korean Languages in the content.
# This will make .Summary and .WordCount behave correctly for CJK languages.
# 中日韩语言请改为 true
hasCJKLanguage = true
googleAnalytics = "G-5C3W6P2YX9"

[author]
    name = "Bladeisme"
    description = "同人女"
    # profile photo of author in author card
    # 作者头像
    image = "/images/author.png"
    # link of followme in author card and footer
    # 作者卡片里 followme 和页脚作者的链接
    link = "https://weibo.com/6500612922"

# Taxonomies
[taxonomies]
    category = "categories"
    tag = "tags"
    series = "series"
    
[params]
enableimgloop = true
showToc = true
    [params.site]
        onlyOneLang = false
        # style of theme: auto, light, dark
        mode = 'auto'

## Waline
    [params.waline]
        enable = true

[[menu.main]]
    name = "主页"
    url = "/"
    weight = 1
    pre = "<i class='fa fa-home'></i>"
[[menu.main]]
    name = "文章"
    url = "/posts"
    weight = 2
    pre = "<i class='fa fa-book'></i>"
[[menu.main]]
    name = "分类"
    url = "/categories"
    weight = 3
    pre = "<i class='fa fa-folder-open'></i>"
[[menu.main]]
    name = "系列"
    url = "/series"
    weight = 4
    pre = "<i class='fa fa-gears'></i>"
[[menu.main]]
    name = "标签"
    url = "/tags"
    weight = 5
    pre = "<i class='fa fa-tags'></i>"        
[[menu.main]]
    name = "关于"
    url = "/about"
    weight = 6
    pre = "<i class='fa fa-info-circle'></i>"
 

    # page configuration
    # 页面配置  
    [params.page]

        # top image in home page, note that the "/" in path is necessary, the same applies below
        # 主页的顶部图，路径开头”/“是必需的。下同
        homeTopImg = "/images/home.jpg"
        # title in home top image, support Markdown
        # 主页标题，支持Markdown语法
        homeTitle = "Kawa1Planet"
        # font size(px)
        # 主页标题字号（单位：px）
        homeTitleFontSize = 35
        # content in home top image, support Markdown
        # 主页内容，支持Markdown语法
        homeContent = "卡哇1星球自转中"
        # font size(px)
        # 主页内容字号（单位：px）
        homeContentFontSize = 20

        # top image in categories terms page
        # 分类页面的顶部图
        categoryTopImg = "/images/categories.jpg"
        # description of categories terms page
        # 子标题

        # top image in series terms page
        # 系列页面的顶部图
        seriesTopImg = "/images/series.jpg"
        # description of series terms page
        # 子标题

        # top image in tags terms page
        # 标签页面的顶部图
        tagTopImg = "/images/tag.jpg"
        # description of tags terms page
        # 子标题

        # top image in allposts page
        # 所有文章页面的顶部图
        allPostsTopImg = "/images/allPosts.jpg"
        # description of allposts page
        # 子标题

        # top image in about page
        # 关于页面的顶部图
        aboutTopImg = "/images/about.jpg"
        # description of about page
        # 子标题
        aboutDes = "The Foxes Come at Night"

        # default image for a post without "image" param
        # 当文章没有设置图片时，将用此图来替代
        postsTopImg = "/images/default.jpg"
        
        # 主页文章最大显示数量
        maxHomePostCount = 6
        # 相关文章最大显示数量
        maxPageRelatedCount = 3
        # 最新文章最大显示数量
        maxPageNewestCount = 3


    # footer
    # 页面底部配置
    [params.footer]
        # whether to enable footer
        enable = true
        # copyright
        copyRight = true
        from = 2022
        # wheher to enable count of visitor and view
        visitor = true
        # wheher to enable theme information
        themeInfo = true


    # aplayer, se  more: https://aplayer.js.org/#/zh-Hans/
    # 音乐播放器配置，详情请移步：https://aplayer.js.org/#/zh-Hans/
    [params.aplayer]
        enable = false
        server = "netease"
        type = "playlist"
        id = 752439587
        fixed = true
        autoplay = false
        loop = "all"
        order = "random"
        preload = "auto"
        list_folded = "ture"
        list_max_height = "500px"
        lrc_type = 1

# related configuration, see more: https://gohugo.io/content-management/related/
# 相关文章的配置。详情请移步：https://gohugo.io/content-management/related/
[related]
    # 取值0-100之间，越小匹配到的文章越多，但准确性稍差
    threshold = 0
    # 允许包含最新的文章
    includeNewer = true
    # 设置为true时，可以在索引和查询中同时使用小写关键字。
    # 这可能会在轻微的性能损失下提供更准确的结果。
    # 也可以在下面的子项中分别设置此值。
    toLower = false

    [[related.indices]]
        # 匹配类别
        name = "categories"
        # 一个整数权重，表示此参数相对于其他参数的重要性。
        # 可以是0，有关闭这个索引的效果，甚至是负数。
        # 使用不同的值进行测试，以查看最适合您的内容的值。
        weight = 100
        # 同上toLower
        toLower = false

    [[related.indices]]
        name = "tags"
        weight = 80
        toLower = false

    [[related.indices]]
        name = "date"
        weight = 10

# Markup related configuration in Hugo
# Hugo 解析文档的配置
[markup]
    # syntax highlight, see more: https://gohugo.io/functions/highlight/
    # 语法高亮，详情请移步：https://gohugo.io/functions/highlight/
    [markup.highlight]
        codeFences = true
        guessSyntax = false
        hl_Lines = ''
        lineAnchors = ''
        lineNoStart = 1
        # 显示每一行代码前的序号
        lineNos = true
        anchorLineNos = false
        lineNumbersInTable = true
        noClasses = false
        noHl = false
        hl_inline = false
        # 代码高亮样式，更多样式请移步：https://xyproto.github.io/splash/docs/
        style = 'monokailight'
        tabWidth = 4

    # enable the following code if there are html statements in your md file
    # 如果md文件中有html语句，请启用以下代码

    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
